# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenieCanHelp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenieCanHelp
  #pod 'Alamofire', '~> 4.7'
  #pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SlideMenuControllerSwift'
  pod 'IQKeyboardManagerSwift'
  #pod 'Kingfisher'
  pod 'RealmSwift'
  #pod 'GoogleAnalytics'
  pod 'Firebase/Core'

end
